[package]
name = "libflock_cpal"
version = "0.0.1"
authors = ["Colin Clark <colinbdclark@gmail.com>"]
edition = "2018"

[dependencies]
cpal = "0.13.1"

[target.'cfg(target_os = "windows")'.dependencies]
cpal = {version = "0.13.1", features = ["asio"]}
clang-sys = "0.29.3"
