[package]
name = "flocking"
version = "0.0.1"
authors = ["Colin Clark <colinbdclark@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.64", default-features = false, features = ["alloc"] }
