[package]
name = "flocking_cpal"
version = "0.0.1"
authors = ["Colin Clark <colinbdclark@gmail.com>"]
edition = "2018"

[dependencies]
flocking = { path = "../flocking" }
cpal = "0.13.3"

[target.'cfg(target_os = "linux")'.dependencies]
cpal = {version = "0.13.3", features = ["jack"]}
