name: build-and-run

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Linux audio dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libasound2-dev jackd2 libjack-jackd2-dev libjack-jackd2-0

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        # From https://github.com/actions/virtual-environments/issues/2528
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Extract-7Zip -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream

      - name: Start jackd on Linux
        if: runner.os == 'Linux'
        run: jackd -r -d dummy &

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: run print_audio_tree example
        env:
          RUST_BACKTRACE: 1
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example print_audio_tree
