name: build-and-run

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install audio dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libasound2-dev

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: run print_audio_tree example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example print_audio_tree
